# Autogenerated wrapper script for gflags_jll for x86_64-apple-darwin
export gflags, gflags_nt

JLLWrappers.@generate_wrapper_header("gflags")
JLLWrappers.@declare_library_product(gflags, "@rpath/libgflags.2.2.dylib")
JLLWrappers.@declare_library_product(gflags_nt, "@rpath/libgflags_nothreads.2.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        gflags,
        "lib/libgflags.2.2.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        gflags_nt,
        "lib/libgflags_nothreads.2.2.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
